[[redirects]]
from = "/about"
to = "/docs/wiki/getting-started"

[[redirects]]
from = "/baro"
to = "/docs/wiki/guides/current/barometer"

[[redirects]]
from = "/development"
to = "/docs/development"

[[redirects]]
from = "/failsafe"
to = "/docs/wiki/guides/current/Failsafe"

[[redirects]]
from = "/guides"
to = "/docs/wiki/guides"

[[redirects]]
from = "/releases"
to = "/docs/category/release-notes"

[[redirects]]
from = "/setup"
to = "/docs/wiki/getting-started/setup-guide"

[[redirects]]
from = "/wiki"
to = "/docs/wiki"